### ISSUE TITLE
Customer > Delete operation returns error

### ISSUE THREAD

**Issue by stephenyeargin** [stripe-contrib/stripe-cli#19]
With things configured, I can run:

```
$ stripe customers find --env=live cus_94bdlpE3TN9ZQq
{
  :id              => "cus_94bdlpE3TN9ZQq",
  :object          => "customer",
  :account_balance => 0,
  :created         => 2016-08-25 13:18:08 -0500,
  :currency        => "usd",
  :default_source  => nil,
  :delinquent      => false,
  [...]
```

But running the following throws an error:

```
$ stripe customers delete --env=live cus_94bdlpE3TN9ZQq
/opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/stripe-1.24.0/lib/stripe/api_operations/request.rb:36:in `request': undefined method `merge' for "sk_live_<key redacted>":String (NoMethodError)
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/stripe-1.24.0/lib/stripe/api_operations/delete.rb:6:in `delete'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/stripe-cli-1.8.3/lib/stripe/cli/command.rb:81:in `request'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/stripe-cli-1.8.3/lib/stripe/cli/command.rb:71:in `delete'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/stripe-cli-1.8.3/lib/stripe/cli/commands/customers.rb:25:in `delete'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:109:in `invoke'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:232:in `block in subcommand'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/stripe-cli-1.8.3/bin/stripe:4:in `<top (required)>'
	from /opt/boxen/rbenv/versions/2.1.2/bin/stripe:23:in `load'
	from /opt/boxen/rbenv/versions/2.1.2/bin/stripe:23:in `<main>'
```

**Comment by OutlawAndy** [comment]
@stephenyeargin Thanks for reporting this!
Definitely a bug.   I'll be releasing a patch shortly.

**Comment by OutlawAndy** [comment]
gem version 1.8.4 includes the fix.  Thanks!

**Comment by stephenyeargin** [comment]
:metal:
