### ISSUE TITLE
No cards method

### ISSUE THREAD

**Issue by alex-cory** [stripe-contrib/stripe-cli#20]
I might be missing something, but after running `stripe cards list --owner=cus_99VKqGSXvCOSnW` I get the following error:

```
/usr/local/lib/ruby/gems/2.3.0/gems/stripe-1.24.0/lib/stripe/stripe_object.rb:241:in `method_missing': undefined method `cards' for #<Stripe::Customer:0x007fa37a4740d0> (NoMethodError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/stripe-cli-1.8.4/lib/stripe/cli/commands/cards.rb:16:in `list'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /usr/local/lib/ruby/gems/2.3.0/gems/stripe-cli-1.8.4/bin/stripe:4:in `<top (required)>'
    from /usr/local/bin/stripe:23:in `load'
    from /usr/local/bin/stripe:23:in `<main>'
```

**Comment by OutlawAndy** [comment]
@alex-cory I'm having trouble reproducing this issue.  Can you tell me what api version your Stripe account is using.  You can find it in your Stripe dashboard, it's the one that looks like a date.
e.g. `2016-07-06`

Thanks!

**Comment by OutlawAndy** [comment]
@alex-cory I'm going to assume this is no longer an issue.

**Comment by alex-cory** [comment]
Sorry for not replying! I totally missed this. It's still happening,  but it very well could be a version thing because in my `~/.stripecli` I don't include a `version = 2016-07-06` field.  Having a hard time finding it on the dashboard.
