### ISSUE TITLE
Missing method error after updating

### ISSUE THREAD

**Issue by ryanwood** [stripe-contrib/stripe-cli#21]
Just updated to 1.8.4 and get this with every command including `stripe help`:

```
/Users/ryanwood/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fc02894ca50 stripe-cli-1.8.4> (NoMethodError)
	from /Users/ryanwood/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/ryanwood/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/ryanwood/.rvm/gems/ruby-2.3.1@global/gems/stripe-cli-1.8.4/bin/stripe:3:in `<top (required)>'
	from /Users/ryanwood/.rvm/gems/ruby-2.3.1@global/bin/stripe:23:in `load'
	from /Users/ryanwood/.rvm/gems/ruby-2.3.1@global/bin/stripe:23:in `<main>'
	from /Users/ryanwood/.rvm/gems/ruby-2.3.1@moonclerk/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ryanwood/.rvm/gems/ruby-2.3.1@moonclerk/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by ryanwood** [comment]
Seems like a similar issue to #20.

**Comment by OutlawAndy** [comment]
okay, so I dug into this a little bit and found [this discussion](https://github.com/remomueller/documentation/issues/7)

Can you confirm that your RubyGems version is prior to 2.6.3?  If so, I think that is the issue.

Please let me know what you find out.  Thanks!

**Comment by ryanwood** [comment]
That was it. I was on 2.5.1. Upgraded to the latest (2.6.7) and it fixed the issue. Thanks!
